### ISSUE TITLE
Question: Business logic of item in viewmodel list

### ISSUE THREAD

**Issue by beaniebag** [FilledStacks/flutter-tutorials#10]
Using your architecture what would you recommend for handling the business logic of an item in the view model's list.  For example, using the post view, I would like to add a checkbox that when clicked will change background for this specific post to green.  Preferably I'd like to include isChecked bool in the post model rather than creating another viewmodel and using post.id as a reference like the likebutton.

**Comment by FilledStacks** [comment]
If it's a non custom check box then I would just keep it all in the ListItem's model. It should be small enough. You can have the check logic in the PostListItem's model. If the checkbox has  custom UI then I would atleast spilt the UI for that checkbox into it's own widget. It doesn't need it's own model, but it'll keep your list item widget code clean so you can just use it like below.

```dart
Row(
children: [ 
  ListDetails(),
  ColorChangeCheckBox(
    onChange: (value) => model.updateColorCheck(value)
  )
]
);
```

Also if you'd like to ask questions you can come over to the [Slack](https://join.slack.com/t/filledstacks/shared_invite/enQtNjY0NTQ3MTYwMzEwLTJjZmU0ODRhOTA5ZGE3MTUxOTUzODdlNzFjMDg0ZGU4ZDQzMzVlMDQ0MzYxZWNhOWViOGI1NjZiZDE1YTQ3NGM) and ask over there.
