### ISSUE TITLE
Unable to supply messageText and titleText as showCustomSnackBar arguments

### ISSUE THREAD

**Issue by EviCoach** [FilledStacks/flutter-tutorials#116]
_snackbarService.showCustomSnackBar(
        duration: Duration(seconds: 2),
        title: exception.toString(),
        variant: SnackbarType.success,
        message: '',
        // message: exception.toString(),
      );

There is no way to receive messageText and title text from the above code snippet to the one below

service.registerCustomSnackbarConfig(
    variant: SnackbarType.success,
    config: SnackbarConfig(
      // padding: EdgeInsets,
      margin: EdgeInsets.symmetric(vertical: 20, horizontal: 30),
      backgroundColor: AppColors.textColor,
      textColor: AppColors.white,
      // titleText: ,
      messageText: Text(
        "",
        textAlign: TextAlign.center,
        style: TextStyle(),
      ),
      borderRadius: 1,
      // dismissDirection: SnackDismissDirection.HORIZONTAL,
    ),
  );

**Comment by FilledStacks** [comment]
Hey, it shows [here](https://pub.dev/packages/stacked_services#snackbar-service) how to do that. 

Register your configs

```dart
void setupSnackbarUi() {
  final service = locator<SnackbarService>();

  service.registerCustomSnackbarConfig(
    variant: SnackbarType.blueAndYellow,
    config: SnackbarConfig(
      backgroundColor: Colors.blueAccent,
      textColor: Colors.yellow,
      borderRadius: 1,
      dismissDirection: SnackDismissDirection.HORIZONTAL,
    ),
  );

  service.registerCustomSnackbarConfig(
    variant: SnackbarType.greenAndRed,
    config: SnackbarConfig(
      backgroundColor: Colors.white,
      titleColor: Colors.green,
      messageColor: Colors.red,
      borderRadius: 1,
    ),
  );
}
```

Show the config
```dart
_snackbarService.showCustomSnackBar(
  variant: SnackbarType.blueAndYellow,
  message: 'Blue and yellow',
  title: 'The message is the message',
  duration: Duration(seconds: 2),
  onTap: (_) {
    print('snackbar tapped');
  },
  mainButtonTitle: 'Undo',
  onMainButtonTapped: () => print('Undo the action!'),
);
```

**Comment by EviCoach** [comment]
There are two other optional arguments, named titleText and messageText that are TextWidget, but I can supply their values when calling 
_snackbarService.showCustomSnackBar(
        duration: Duration(seconds: 2),
        title: exception.toString(),
        variant: SnackbarType.success,
        message: '',
        // message: exception.toString(),
      );
I need those two arguments to be able to center align the title and the message. currently they are left aligned and there is no way to center them

**Comment by FilledStacks** [comment]
@EviCoach you won't be able to pass a widget directly into it. I don't mix UI code and business logic. I've added `titleTextAlign` and `messageTextAlign` to the snackbarConfig model. Let me know if it works. v 0.6.6

**Comment by EviCoach** [comment]
It's working fine now. Thank you very much
