### ISSUE TITLE
Shared Preferences injection error using Stacked

### ISSUE THREAD

**Issue by JasmeetSingh30** [FilledStacks/flutter-tutorials#124]
Hey Dane, Hope you are doing good this pandemic. I am creating an app where I need to use Shared preferenes and while donig dependecy injection and let it get generated its giving me below error. PLease help me out.

![issue1](https://user-images.githubusercontent.com/43646467/115863593-52017480-a453-11eb-9e4a-17fe170fb1f8.png)
![image](https://user-images.githubusercontent.com/43646467/115863649-647bae00-a453-11eb-98ce-b7efc3a3b6c3.png)

**Comment by harriseldon** [comment]
I did get it to not have errors with a few modifications.
1. within the app.dart, presolveUsing: LocalStorageServiceShared.getInstanceReady
Notice that it is the actual function name. When the build_runner runs, it will covert it to the async function call
2. Null safety requires that you declare _instance as LocalStorageServiceShared?, but locator cannot resolve this to LocalStorageServiceShared. Therefore I changed your getInstanceReady function definition to not include the ? in type definition and changed the return to also do an explicit cast to LocalStorageServiceShared.

``` code
dependencies: [
  Presolve(
      classType: LocalStorageServiceShared,
      presolveUsing: LocalStorageServiceShared.getInstanceReady),
]
```


``` code
import 'package:shared_preferences/shared_preferences.dart';

class LocalStorageServiceShared {
  static LocalStorageServiceShared? _instance;
  static SharedPreferences? _preferences;
  
  // Changed from Future<LocalStorageServiceShared?> to Future<LocalStorageServiceShared>
  static Future<LocalStorageServiceShared> getInstanceReady() async {
    if (_instance == null) {
      _instance = LocalStorageServiceShared();
    }
    if (_preferences == null) {
      _preferences = await SharedPreferences.getInstance();
    }
    // Added explicit cast
    return (_instance as LocalStorageServiceShared);
  }
}
```

The resulting app.locator.dart now looks as follows
```  code
Future setupLocator() async {
  final localStorageServiceShared =
      await LocalStorageServiceShared.getInstanceReady();
  locator.registerSingleton(localStorageServiceShared);
}
```
Notice how the getInstanceReady was properly converted to the function getInstanceReady()

```

**Comment by JasmeetSingh30** [comment]
Awesome it worked. Thank you soooo much dude!!!!!! Now i know that i lack knowledge on null safety and OOP. Can you help me get a guide on these and anything more which will help me understand these basic concepts , i have just started with dart and flutter.
