### ISSUE TITLE
Navigation Service and null safety

### ISSUE THREAD

**Issue by JavierPerezLavadie** [FilledStacks/flutter-tutorials#136]
Hey hello I appreciate your videos thanks for that.

I currently have a problem with the navigation service and null safety security. Can you tell me how I can make this tutorial code compatible with non-null security? Thank you.

Can you also tell me how to add animations to the routes generated in this way?

```
import` 'package:flutter/material.dart';

class NavigationService {
  GlobalKey<NavigatorState> _navigationKey = GlobalKey<NavigatorState>();

  GlobalKey<NavigatorState> get navigationKey => _navigationKey;

  void pop() {
    return _navigationKey.currentState.pop();
  }

  Future<dynamic> navigateTo(String? routeName, {dynamic arguments}) {
    return _navigationKey.currentState
        .pushNamed(routeName, arguments: arguments);
  }
} 

```
Thanks a lot for your help

**Comment by fairlycasual** [comment]
Combining the base architecture with the other navigation tutorial found [here](https://www.filledstacks.com/post/navigate-without-build-context-in-flutter-using-a-navigation-service/) solved this issue for me.
