### ISSUE TITLE
validationMessage not implemented in 014

### ISSUE THREAD

**Issue by lookfirst** [FilledStacks/flutter-tutorials#14]
https://github.com/FilledStacks/flutter-tutorials/blob/master/014-provider-v3-updates/2-final/lib/ui/views/login_view.dart

Thank you so much for creating these tutorials, unbelievably helpful! Providers is totally awesome and this example helps me understand it so much!

Would you mind implementing validationMessage in 014? I'm having trouble understanding the logic since BaseWidget gets passed in the child now and it doesn't cause it to render when the message changes.

Also, you're missing a dispose() of the controller in the above file.

**Comment by FilledStacks** [comment]
Hey, thanks. I'm happy I could help 😀 

I didn't implement the validation message because it would be the exact same as in 10. I don't know what you mean by "base_widget gets passed in the child now" it's the same setup as 10, the only difference is that we're constructing the viewmodel our selves and using provider to inject the services. The only difference between this architecture and the one in 10 is that we're not using get_it so the implementation of everything else will be the same.

**Comment by lookfirst** [comment]
It isn't exact same as 010... try implementing it in 014 and see...

What I mean by base_widget gets passe din the child now... is the difference between this:

https://github.com/FilledStacks/flutter-tutorials/blob/589e23c9578f375b132c39581883f621c5100bd3/010-provider-architecture/002-final-no-getit/lib/ui/views/login_view.dart#L31

and this:

https://github.com/FilledStacks/flutter-tutorials/blob/master/014-provider-v3-updates/2-final/lib/ui/views/login_view.dart#L22

Tell me how you'd pass the validationMessage into LoginHeader in that second example.

re: controller, just pointing it out since you did implement it before and given it is documented best practice to do so, seemed like something you're missing. I'd hate for a new person like me to come along and only see 014 and not implement it because they didn't know to implement it.

**Comment by FilledStacks** [comment]
Oooh that. Yes I thought I made it clear in the video that I just wanted to demo that for when you have a static set of widgets that won't change. Take it out of the child and add it into the builder where you can update the error then everything will be the same once you call notifyListeners (). A lot of the things in the video is to show how to use it in the architecture. I wouldn't even provide the user through the StreamProvider, it was just to show the functionality. Instead I'll have a currenUser property on the baseModel and access it there if required.

So remove the login header as a static child, use it in the builder and pass the error message to it like in 10.

________________________________

**Comment by lookfirst** [comment]
With regards to the user stuff, do you have an example of how you'd do it? How do you set the user for each view?

**Comment by FilledStacks** [comment]
In the base model I have a property that gets my user

```dart
User get currentUser => locator<AuthenticationService>().user;
```

Then every view / model has access through it with user.model. I do this for larger users, then I have reducers on my model that inherits from that for additional data things like

```dart
String get authorTitle => translator(Strings.TitleTag) + user.fullName;
```

And I bind to those property reducers. I don’t have an example I can share, but that’s all that I do when it comes to exposing the user in every model.

Regards,
Dane Mackier

________________________________

**Comment by lookfirst** [comment]
Thanks for all your help. Closing...
