### ISSUE TITLE
Items getting disposed when using two or more slivers or listview builders while  using Provider 

### ISSUE THREAD

**Issue by Sameerkash** [FilledStacks/flutter-tutorials#18]
I'm trying to implement two sliver widgets within a custom scroll view, and I'm facing a problem with the state of the data being passed in the Listview Builder which is the same case with the 
 sliverbuilderlist once I scroll down and come back up the items in the list are disposed and hence I'm getting an error. This is happening only when I use two or more sliver widgets together, the sliver list on its own is fine, right now I'm implementing a collapsable sliverappbar with two tabs, and I'm passing a ListviewBuilder two one of the tabs, and I get an error when I scroll down and up again after a few seconds, please help me understand the problem.

I tried keeping it alive with keepalive mixin but it didn't work 

feed[i] paints objects from the Provider Feed

```
class FeedItemScreen extends StatefulWidget {
  @override
  _FeedItemScreenState createState() => _FeedItemScreenState();
}

class _FeedItemScreenState extends State<FeedItemScreen> with  AutomaticKeepAliveClientMixin<FeedItemScreen>
{
  @override
  Widget build(BuildContext context) {
    final feedData = Provider.of<Feed>(context);
    final feed = feedData.items;

    return ListView.builder(
           itemBuilder: (context, i) => ChangeNotifierProvider(
              builder: (ctx) => feed[i],
              child: FeedsItem(),
            ),
            itemCount: feed.length,
    );
  }

  @override
  bool get wantKeepAlive => true;
}


inside Defaulttabcontroller : I'm passing FeedScreen(), which builds the list to one of the tabs 

  body:  TabBarView(
              children: <Widget>[
                 new NotificationScreen(),
                new FeedScreen(),



```
I'm using the feed[i] items in another file to access the constructor of the FeedItem and its elements and display the relevant data 

/flutter ( 5092): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5092): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter ( 5092): A FeedItem was used after being disposed.
I/flutter ( 5092): Once you have called dispose() on a FeedItem, it can no longer be used.

FeedItem is the class which my data is passed to, and this is the error I'm getting, I'm getting the same error when using multiple slivers within a single viewport. or multiple scrollable list views bascially

**Comment by FilledStacks** [comment]
Hi Sorry I never got to this. Client work is hectic, I still have a company to run :) 

Keep local references to your widgets and pass that into your list. This will avoid the widget being rebuilt. Make sure in the dispose of the view you dispose those local widgets as well.
