### ISSUE TITLE
"architecutre" instead of "architecture"

### ISSUE THREAD

**Issue by rowild** [FilledStacks/flutter-tutorials#19]
Hi! if you ever find some time, you may want to fix the spelling error in project No 10.

architecutre   -->   architecture

From what I saw, you use it consequently throughout the code (which should make it work - not tested), but since you use the proper spelling the the Readme, it might still cause confusion aat some point and is probably a potential source of error.

**Comment by FilledStacks** [comment]
Haha :) I've never been one for spell checkers. I should probably 100% use one while writing. Could I ask you to Do a pull request and fix it 😅 ? time is scarce, I'm always writing a new tutorial

**Comment by rowild** [comment]
Sure! - I am a proof reader, and believe me: it sucks to see errors all the time! It takes away from the reading flow and in general from a joyful reading experience! I wish I could turn it off and oversee errors and just go reading with the intended meaning... Consider yourself happy NOT to suffer from such an annoying habbit! :-)
PR coming up.
