### ISSUE TITLE
Hi guy, in in example 002-final-no-getit path library was not found

### ISSUE THREAD

**Issue by maithanhphuongbt** [FilledStacks/flutter-tutorials#23]
provider:
    git:
      url: https://github.com/rrousselGit/provider
      ref: proxy-provider

**Comment by FilledStacks** [comment]
Yeah that was just an example of how it could be used. That example was given before v3 was out. It's not working. Look at the V3 provider architecture if you want to see how to use proxy provider.

________________________________
