### ISSUE TITLE
Dispose issue in feedback tutorial

### ISSUE THREAD

**Issue by ericklhe** [FilledStacks/flutter-tutorials#24]
Hi @FilledStacks ,

I would like to thank you for the awesome job you're doing. I love the architecture you proposed. 
I'm trying to implement the real stats tutorial using get it and provider. 

The issue is that using registerFactory I get the following: "Stream has already been listened too."

I followed your suggestion on the [Dispose issue in provider architecture part 2](https://github.com/FilledStacks/flutter-tutorials/issues/6), and I implemented the following code:

```
StreamSubscription<List<UserFeedback>> subscription;

  FeedbackViewModel() {
    subscription = _firestoreService.feedback.listen(_onFeedbackUpdated);
  }

  @override
  void dispose() {
    subscription.cancel();
    super.dispose();
  }
```

I'm still having the same issue.

Now, if I implement the following code: ``` locator.registerSingleton(FeedbackViewModel()); ``` , 
remove the dispose method and the subscription variable, I get the following error: 

"A FeedbackViewModel was used after being disposed. Once you have called dispose() on a FeedbackViewModel, it can no longer be used."

Did you find a way around this bug?

Regards,

**Comment by FilledStacks** [comment]
Hi @ericklhe 

Thanks for the nice words. I'm happy to have helped.

1. You have to make sure that your BaseView or BaseWidget is not overriding dispose and calling it on the model. Provider does that automatically. That should take care of the "Once you have called dispose" bug.

2. If you watch my [Beginners Guide to Streams](https://youtu.be/53jIxLiCv2E) I go over why you get that error. In short Cancelling a subscription won't make it go away, Dart has two types of streams. Single subscription (default) and broadcast. I go into depth on why it's like that and what their intention was. Both can be used for the same thing, but single subscription is better suited for something else.

**Comment by ericklhe** [comment]
Nice. 

1. How can I make sure that the baseview is not overriding the dispose method? Do you have an example of that?

2. I read the beginners guide to streams, and the solution you proposed is to convert the single subscription to a broadcast one. In this scenario, I have to declare the stream as a broadcast on firebaseService, then listen to it in Feedback View Model and manually dispose it on the same feedback view model? Won't that be affected also by the baseview?
How do I implement that?
Regards,

**Comment by FilledStacks** [comment]
1. Oh, if there's no override in the base view then that's not the case. Something else is disposing of your model before provider does, or you're re-using the same model again.

2. That won't be affected by the BaseView. The goal of the base view is to collect very specific shared code like passing a model to a `ChangeNotifierProvider` and passing in the builder, as well as have `onModelReady` functionality at an architecture level. Other than that it doesn't care about the implementation of the model or your view. You can dispose of the stream manually as you do in your code above. Nothing changes besides making the controller a broadcast stream.

If you're still dealing with the dispose problem, figure out when it's being called and what is calling it then make it stop, or dispose of it and create a new instance since that clearly won't require any state to be carried over if it's being disposed.

**Comment by ericklhe** [comment]
1. I'm using ```registerSingleton(FeedbackViewModel())```, hence using the same instance.  I have the following on the firestore_service.dart:
```
// Constructor
FirestoreService() {
// ....
Firestore.instance
        .collection("feedback")
        .where("open", isEqualTo: true)
        .snapshots()
        .listen(_feedbackAdded); 
}

// ...
final StreamController<List<UserFeedback>> _userFeedbackController =
      StreamController<List<UserFeedback>>();

Stream<List<UserFeedback>> get feedback => _userFeedbackController.stream;

// ....

```
On the FeedbackViewModel I have the following:
```
// ...
FirestoreService _firestoreService = locator<FirestoreService>();
List<UserFeedback> userFeedback;

// constructor
FeedbackViewModel() {
    _firestoreService.feedback.listen(_onFeedbackUpdated);
  }
```
I don't have a dispose there.

I think the issue is with the ChangeNotifierProvider on the baseview. I left everything as-is and implement the following code:

BaseView Before:
```
@override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      builder: (context) => model,
      child: Consumer<T>(
        builder: widget.builder,
      ),
    );
  }

```

BaseView After:
```
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider.value(
      value: model,
      child: Consumer<T>(
        builder: widget.builder,
      ),
    );
  }
```
I don't get that issue anymore. I'm not implementing the dispose method anywhere in the code.

2. 

**Case 2.1a** - Leaving the code above as-is and using ```registerSingleton(FeedbackViewModel())```

Leaving the code above as-is, using the builder method of ChangeNotifierProvider and registring ```registerSingleton(FeedbackViewModel())``` is giving me the  "A FeedbackViewModel was used after being disposed. Once you have called dispose() on a FeedbackViewModel, it can no longer be used." error. 

**Case 2.1b** - Implementing the broadcast solution and using ```registerSingleton(FeedbackViewModel())```

Now, if I implement the broadcast solution using ```registerSingleton(FeedbackViewModel())```  and leaving the BaseView as-is, the code on firestoreService is the following:
``` final StreamController<List<UserFeedback>> _userFeedbackController =
      StreamController<List<UserFeedback>>.broadcast();```

Then, on FeedbackViewModel I have the following code:
```
StreamSubscription<List<UserFeedback>> subscription;

  FeedbackViewModel() {
    subscription = _firestoreService.feedback
        .asBroadcastStream()
        .listen(_onFeedbackUpdated);
    // _firestoreService.feedback.listen(_onFeedbackUpdated);
  }

  @override
  void dispose() {
    super.dispose();
    subscription.cancel();
  } ```

I get the same error: 

"A FeedbackViewModel was used after being disposed. Once you have called dispose() on a FeedbackViewModel, it can no longer be used." 

**Case 2.2a** - Leaving the code above as-is and using ```registerFactory(() =>FeedbackViewModel())```

In this scenario, I get the following error:
``` Bad state: Stream has already been listened to.```



**Case 2.2b** - Implementing the broadcast solution and using  ```registerFactory(() =>FeedbackViewModel())```

In this scenario I'm getting the following error:
```
The getter 'length' was called on null.
Receiver: null
Tried calling: length 
```

**Comment by ericklhe** [comment]
Hi @FilledStacks,

I found an explanation of why we use ChangeNotifierProvider.value instead of ChangeNotifierProvider.

This explanation comes from [Maximilian Schwarzmüller](https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps):

```
//  We use **ChangeNotifierProvider.value** instead of ChangeNotifierProvider
//  with builder if we are using a list or a grid because if we use the
//  latter with a list or grid we are recycling the widget
//  and we can get random errors using this approach.

//  By using ChangeNotifierProvider.value we are actually making sure
//  that the provider works even if the  data changes for the widget
//  because the provider is tied to its data and is attached and detached
//  to and from the widget instead of changing data being attached to
//  the same provider.

```
That would make the implementation easier since we can use registerSingleton and the default stream config.

Let me know what you think of this approach.

regards,

**Comment by FilledStacks** [comment]
I think it's perfectly fine for your situation.

If you follow my original tutorial I do show that when you want to get the inherited dispose functionality you would use the Default constructor, otherwise you'd use the .value named constructor.

I think it's fine, every situation calls for a different solution :)

**Comment by ericklhe** [comment]
Nice. I didn't get this dispose issue in the provider architecture tutorial. I'll be using your architecture and the . value since we're always dealing with listviews or gridviews, hehe.

Regards.

**Comment by ericklhe** [comment]
Hi @FilledStacks ,

Sorry for all the questions, hehe. 

I added an AuthService to this example. I register the AuthService is a LazySingleton and called it in the base model. Here's the issue. When I logout and login again, I get the ```Bad state: Stream has already been listened to.``` error.

I tried converting the stats controller to broadcast - 
```final StreamController<Stats> _statsController = StreamController<Stats>.broadcast(); ```  

but by doing that now I get the following error:

```
The getter 'errorCount' was called on null.
Receiver: null
Tried calling: errorCount
```

I think if I can understand this implementation, I'll tackle any state management issue with this architecture.

Regards,

**Comment by FilledStacks** [comment]
Hey man,

Null exceptions are very code specific. Something is null. I suggest going through my logging tutorial, not even the setting up part, just the rules on when and where to log, then you'll definitely be able to find the error. You have to find what's null then fix that, the architecture has very little to do with null exceptions. That's an implementation detail.

________________________________
