### ISSUE TITLE
27-location-service main.dart  The return type 'Stream<userLocation> is not a StreamController<userLocation> as defined by anonmyous closure

### ISSUE THREAD

**Issue by billyurs** [FilledStacks/flutter-tutorials#27]
I am getting error at this line 

  @override
  Widget build(BuildContext context) {
    return StreamProvider<UserLocation>(
        builder: (context) => LocationService().locationStream,
        child: MaterialApp(title: 'Flutter Demo', home: HomeView()));
  }

**Comment by FilledStacks** [comment]
You should read what the error is and then fix it 😄

**Comment by Tabarek** [comment]
use
 **StreamProvider<userLocation>.controller**
instead of **StreamProvider**

**Comment by rizerzero** [comment]
StreamProvider<ConnectivityStatusEnum>(
    create: (context) => ConnectivityService().connectionStatusController.stream,
  )

**Comment by c-shashank** [comment]
I get the error error: The argument type 'Widget Function(BuildContext)' can't be assigned to the parameter type 'Widget Function(BuildContext, Widget)'. (argument_type_not_assignable at [appint] lib/main.dart:32) when I try to put this in main.dart

**Comment by FilledStacks** [comment]
@c-shashank seems like you're trying to supply a Widget where it expects a function that returns a widget. Use

```
(context) => Widget()
```

instead of 

```
Widget()
```
