### ISSUE TITLE
033 Episode_Exception caught by rendering library

### ISSUE THREAD

**Issue by kartikgupta1072** [FilledStacks/flutter-tutorials#28]
══ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 6.0 pixels on the bottom.

The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

**Comment by FilledStacks** [comment]
One of your widgets are not big enough to contain the content that's in it
