### ISSUE TITLE
033_Drawer not showing

### ISSUE THREAD

**Issue by kartikgupta1072** [FilledStacks/flutter-tutorials#29]

**Comment by dennis-szymanski** [comment]
Seems to be a bug when deploying to web .. When you run it on an android-emulator it works

**Comment by FilledStacks** [comment]
I saw that too in the last tutorial. I'll look into it and see what's causing it.

**Comment by rmazur** [comment]
Hi,

Just a quick update.
I have tested it with the following:
Flutter 1.13.6-pre.16 • channel master • https://github.com/flutter/flutter.git
Framework • revision fcaf9c4070 (2 days ago) • 2019-12-21 14:03:01 -0800
Engine • revision 33813929e3
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)

And everything works fine including the Drawer.

**Comment by FilledStacks** [comment]
Nice. i know it was working in the demo and the videos and we changed nothing.

Thanks for letting me know it works. I appreciate it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ka822** [comment]
The drawer seems like cannot open for web.

**Comment by FilledStacks** [comment]
Yep. it happens on some versions of Flutter. check the comment above and try the same version out.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
