### ISSUE TITLE
021-completer_dialogs - Error on locator.dart

### ISSUE THREAD

**Issue by cristianfb1989** [FilledStacks/flutter-tutorials#30]
How can I resolve this error? Thank you!
![2019-11-19_11-33-01](https://user-images.githubusercontent.com/16965222/69155591-c3036680-0ac0-11ea-95cb-bc696c772834.png)

**Comment by FilledStacks** [comment]
You have to use the new instance property.

```
GetIt locator = GetIt.instance;
```

Regards,
Dane Mackier

________________________________

**Comment by cristianfb1989** [comment]
Thx you, Dane Mackier! it's works!
