### ISSUE TITLE
011-network-sensitive-ui, the StreamProvider already deprecated builder and change it to create.

### ISSUE THREAD

**Issue by elliotxin** [FilledStacks/flutter-tutorials#33]
In Provider 3.2.0, it's already can not be used "builder" in StreamProvider, the error will come out, please change this to create, thanks a lot.

**Comment by FilledStacks** [comment]
You should do it and make a pull request 😁

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by elliotxin** [comment]
ok, I will do it.
