### ISSUE TITLE
I'm having issues with the architecture provider v3 tutorial

### ISSUE THREAD

**Issue by aguilard07** [FilledStacks/flutter-tutorials#34]
Hello, I followed your tutorial, change the deprecated aspects for the correct ones and now I'm having this issue that Idk how to fix:

`I/flutter (17376): The following assertion was thrown building BaseWidget<LoginViewModel>(dirty, state:`
`I/flutter (17376): _BaseWidgetState<ChangeNotifier>#04890):`
`I/flutter (17376): type '(BuildContext, LoginViewModel, Widget) => Scaffold' is not a subtype of type '(BuildContext,`
`/flutter (17376): ChangeNotifier, Widget) => Widget'`

**Comment by FilledStacks** [comment]
Make sure you pass the generic type <T> everywhere you're expecting the type. In The builder function, class types, everywhere. It's won't infer the type, you have to make it generic.

**Comment by rujulmobilfirst** [comment]
![image](https://user-images.githubusercontent.com/59044757/85600396-12b79b00-b66b-11ea-8699-98297a582690.png)
i also came across this error i forgot to infer generic type at location. this comment is just to help others who might be facing same issue

**Comment by FilledStacks** [comment]
@rujulmobilfirst happened to me once or twice too. Now that i've moved over to stacked it's never happened again.
