### ISSUE TITLE
Mouse Tracking issue

### ISSUE THREAD

**Issue by hardikdhola** [FilledStacks/flutter-tutorials#36]
**- i have facing below error. check my code.**

═══════════════════════════════════════════════════════
════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
The following JSNoSuchMethodError was thrown while routing a pointer event:
NoSuchMethodError: invalid member on null: 'style'

When the exception was thrown, this was the stack: 
package:flutter_demo/extensions/HoverExtensions.dart 12:46                        
package:flutter/src/rendering/proxy_box.dart 2742:22                             
package:flutter/src/gestures/mouse_tracking.dart 434:21                           _dispatchDeviceCallbacks
package:flutter/src/gestures/mouse_tracking.dart 250:9                            
package:flutter/src/gestures/mouse_tracking.dart 365:26  

════════ (2) Exception caught by scheduler library ═════════════════════════════════════════════════
Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:454:12
!_duringDeviceUpdate
is not true
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by gesture library ═══════════════════════════════════════════════════
Assertion failed: org-dartlang-app:///packages/flutter/src/gestures/mouse_tracking.dart:330:12
!_duringDeviceUpdate
is not true
═══════════════════════════════════════════════════════

**My Code**
### HoverExtensions.dart
extension HoverExtensions on Widget {
  static final appContainer =
      html.window.document.getElementById('app-container');

  Widget get showCursorOnHover {
    return MouseRegion(
      child: this,
      onHover: (event) => appContainer.style.cursor = 'pointer',
      onExit: (event) => appContainer.style.cursor = 'default',
    );
  }

  Widget get moveUpOnHover {
    return TranslateOnHover(
      child: this,
    );
  }
}

### TranslateOnHover.dart
class TranslateOnHover extends StatefulWidget {
  final Widget child;

  const TranslateOnHover({Key key, this.child}) : super(key: key);

  @override
  _TranslateOnHoverState createState() => _TranslateOnHoverState();
}

class _TranslateOnHoverState extends State<TranslateOnHover> {
  final nonHoverTransform = Matrix4.identity();
  final hoverTransform = Matrix4.identity()..translate(0, -5, 0);

  bool _hovering = false;

  @override
  Widget build(BuildContext context) {
    return MouseRegion(
      onEnter: (event) => _mouseEnter(true),
      onExit: (event) => _mouseEnter(false),
      child: AnimatedContainer(
        duration: Duration(milliseconds: 200),
        child: widget.child,
        transform: _hovering ? hoverTransform : nonHoverTransform,
      ),
    );
  }

  _mouseEnter(bool hovering) {
    setState(() {
      _hovering = hovering;
    });
  }
}

**Comment by FilledStacks** [comment]
Make sure your Id in the html match the one you're trying to set the mouse style on.

**Comment by hardikdhola** [comment]
- yes my id is same in the index.html.

```
<body id="app-container">
<script src="main.dart.js" type="application/javascript"></script>
</body>
```

**Comment by FilledStacks** [comment]
Then I don't know man. You should probably stay of flutter web because you'll be dealing with a lot of issues. If you're like me and you like finding and solving problems then stay on it and fix it up :)

**Comment by fldvlpr** [comment]
@hardikdhola @FilledStacks I'm also facing the same issue.

did you got any fix?
