### ISSUE TITLE
021 & 037: how to manage the onGenerateRoute

### ISSUE THREAD

**Issue by jasonlaw** [FilledStacks/flutter-tutorials#37]
Hi @FilledStacks ,

How to manage the onGenerateRoute to cater for both case 021 & 037?

021 - Completer dialog
037 - Advance url for web

![image](https://user-images.githubusercontent.com/107820/74009153-9410d880-49bd-11ea-89c7-cd36cafcfc90.png)

![image](https://user-images.githubusercontent.com/107820/74009736-d4bd2180-49be-11ea-93ac-77546cac3662.png)

**Comment by FilledStacks** [comment]
H @jasonlaw , I don't quite know what the problem is. It seems your missing the extension for getRoutingData that returns the RoutingData object.

**Comment by jasonlaw** [comment]
Sorry I was confuse before, it is not about onGenerateRoute actually.

I had followed your 021 course for Dialog Manager and I really like the idea.
At the same time I am looking for a neat way to handle the navigation and I found your course 037. 

It so happen that both also using the MaterialApp builder delegation, so I am wondering how to handle that for both cases.

Like in the screen shot, for Dialog Manager the builder returning the Navigator, and the other one is returning LayoutTemplate.

Thank you!

**Comment by FilledStacks** [comment]
oh, you wrap the child with layout manager in the builder function. or you wrap your dialog manager, it's  just a widget so you can wrap it around any other widget.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jasonlaw** [comment]
You mean (based on the dialog manager screen shot above) :

DialogManager(
     child: LayoutTemplate(
                   child: widget,), 
)

**Comment by jasonlaw** [comment]
To be more clear, I would like to combine both LayoutTemplate and DialogManager for my app.
Thanks.

**Comment by FilledStacks** [comment]
That is how you would combine it. I wrap all mine in eachother. all the managers and any other widget using the builder function.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jasonlaw** [comment]
Clear now, thank you very much! :)
