### ISSUE TITLE
039 Unhandled Exception: NoSuchMethodError: Class 'NoSuchMethodError' has no instance getter 'message'.

### ISSUE THREAD

**Issue by jrmgarcia** [FilledStacks/flutter-tutorials#38]
> E/flutter (14386): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: Class 'NoSuchMethodError' has no instance getter 'message'.
E/flutter (14386): Receiver: Instance of 'NoSuchMethodError'
E/flutter (14386): Tried calling: message
E/flutter (14386): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
E/flutter (14386): #1      FirestoreService.getUser 
package:pasabay_app/services/firestore_service.dart:21
E/flutter (14386): <asynchronous suspension>
E/flutter (14386): #2      AuthenticationService._populateCurrentUser 
package:pasabay_app/services/authentication_service.dart:74
E/flutter (14386): #3      AuthenticationService.isUserLoggedIn 
package:pasabay_app/services/authentication_service.dart:68
E/flutter (14386): <asynchronous suspension>
E/flutter (14386): #4      StartUpViewModel.handleStartUpLogic 
package:pasabay_app/viewmodels/startup_view_model.dart:14
E/flutter (14386): #5      StartUpView.build.<anonymous closure> 
package:pasabay_app/…/views/startup_view.dart:13
E/flutter (14386): #6      _ViewModelProviderState.initState (package:provider_architecture/viewmodel_provider.dart)

**Comment by FilledStacks** [comment]
There's no method `message` on the user object. Or aleast that's what it looks like it's complaining about. Debug it and let me know what the problem is.
