### ISSUE TITLE
034 Flutter Web Template....  pop issue

### ISSUE THREAD

**Issue by vinceyoumans** [FilledStacks/flutter-tutorials#39]
Anychance someone could look at tis issue...    

Dane Mackier

https://stackoverflow.com/questions/60152366/flutter-web-layout-templates-pop-returning-void-but-expects-bool

I am trying to follow along on the 3rd video of the tutorial

**Comment by FilledStacks** [comment]
Remove the type from the function and make it void and remove the return

```dart
void pop() {
 _navigatorKey.currentState.pop();
}
```
