### ISSUE TITLE
Issue with Models in provider architecture

### ISSUE THREAD

**Issue by aguilard07** [FilledStacks/flutter-tutorials#40]
HEllo, I've following your awsome tutorials for a while and I've having this issue with de provider architecture:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: A SignInModel was used after being disposed. E/flutter (32380): Once you have called dispose() on a SignInModel, it can no longer be used.`

Idk if you can help me with that.

**Comment by FilledStacks** [comment]
Remove the dispose call, or use the ChangeNotifier.value constructor to avoid disposing the viewmodel. The [provider_architecture package](https://pub.dev/packages/provider_architecture) has everything in there that you'd need to use my MVVM architecture.
