### ISSUE TITLE
Improvement to ServiceNavigation for AppBar back button

### ISSUE THREAD

**Issue by camillo777** [FilledStacks/flutter-tutorials#42]
In StartupViewModel change: 

`_navigationService.navigateTo(RoutePaths.Home);`
to
`_navigationService.replaceTo(RoutePaths.Home);`

In NavigationService add:

```
Future<dynamic> replaceTo(String routeName, {dynamic arguments}) {
    return _navigationKey.currentState
        .pushReplacementNamed(routeName, arguments: arguments);
  }
```

This will avoid the Back icon on home page resetting the navigation state.

**Comment by ceag235** [comment]
I have tried the above solution but still getting the backbutton taking me to the StartUp View

**Comment by FilledStacks** [comment]
Hey camillo, thanks. I do that in production. You're happy to fix it up in the code and make a pr.
