### ISSUE TITLE
Request permission to translate your articles to Chinese

### ISSUE THREAD

**Issue by eltonlau1994** [FilledStacks/flutter-tutorials#44]
Hi Mackier,

I am Elton from Hong Kong. Thanks for sharing the brilliant architecture and design of using provider package. Beforehand, I found there are quite a lot of ways of implementing provider package, but your is the first that implements this in an elegant way, and your posts and YouTube videos explained it well.

As a result, I want to translate your posts into Traditional Chinese and post them onto Medium (and of coz are free for the public) so that more ppl can know about this design.

Thanks,
Elton Lau

**Comment by FilledStacks** [comment]
Hi Elton,

Thank you very much. I appreciate the kind words about my approach. I would be very happy if you could translate it for the Chinese community.

If you could mention the original post, the website or the YouTube channel I would appreciate it greatly.

We could even add it to the website at some point. I don't have time or the resources in terms of devs at the moment to add localisation for different languages, but i would definitely be open to that.

The website is built it vuejs / gridsome.

For now you can translate and post on Medium, we can discuss more later.

-Dane

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by eltonlau1994** [comment]
Hi Mackier,

Thanks a lot! I am drafting right away. Keep you posted on the progress.

Best regards,
Elton Lau
