### ISSUE TITLE
Update repo with Provider 4

### ISSUE THREAD

**Issue by pdmshrestha** [FilledStacks/flutter-tutorials#45]
Hi,

@FilledStacks  Thanks for the awesome repo. Any plans for updating the repo with updated provider package?

**Comment by FilledStacks** [comment]
Hi Padam,

No plans to do that at all. i only use the change notifier provider and since the only thing that changed is the builder name to create I don't think it's worth updating.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pdmshrestha** [comment]
Hi, thanks for prompt reply.
