### ISSUE TITLE
A value of type 'void' can't be returned from method 'pop' because it has a return type of 'bool'.

### ISSUE THREAD

**Issue by manesvenom** [FilledStacks/flutter-tutorials#48]
In tutorial 043-firebase-push-notifications , the pop() method of navigation_service.dart, it throws A value of type 'void' can't be returned from method 'pop' because it has a return type of 'bool'.

It seems that the _navigationKey.currentState.pop() would return void instead of bool

**Comment by FilledStacks** [comment]
Yup. It changed recently.  remove return and call pop only without returning. or change the function signature to return void

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
