### ISSUE TITLE
Layout Templates for Flutter Web error in NavigationService goBack

### ISSUE THREAD

**Issue by alanlopcu** [FilledStacks/flutter-tutorials#51]
Hello. Thanks for your videos.
The function goBack class NavigationService in project Layout Templates for Flutter Web  (part 3) I'm getting an error that says:

```
{
	"resource": ".../flutter-tutorials/037-advanced-web-navigation/00-starting/lib/services/navigation_service.dart",
	"owner": "dart",
	"code": "return_of_invalid_type",
	"severity": 8,
	"message": "A value of type 'void' can't be returned from method 'goBack' because it has a return type of 'bool'.",
	"source": "dart",
	"startLineNumber": 11,
	"startColumn": 12,
	"endLineNumber": 11,
	"endColumn": 43,
	"tags": []
}
```

Can you please tell me why this is going on? Thank you in advance.

**Comment by FilledStacks** [comment]
You can’t return a void when the function says it’ll return a bool.

Either change the function signature to return a void or remove the return keyword infront of the pop call. OR both.

Regards,
Dane Mackier
