### ISSUE TITLE
012-provider-architecture-pt2 - Number of Like  in HomeView  does not update automatically 

### ISSUE THREAD

**Issue by manesvenom** [FilledStacks/flutter-tutorials#53]
The 012-provider-architecture part 2 final could run smoothly on a real Android device.

When a post is selected and it goes to the PostListItem View then  tap the Like button for a few times, the Like does increase in PostListItem View.  However, it seems the notifyListeners() method has no effect when I go back to the HomeView using the back button . I need to refresh the page by drag down the scroll list again to reveal the updated Like number.

My flutter SDK version is 1.16.2-pre.41
LG D858HK (android-arm)

**Comment by FilledStacks** [comment]
My tutorials cover implementation patterns an principles. Not implementation details. The code won't work 100% there's tons of error handling to do but I can't do all that and stay on point for a video. You'll have to debug that problem and figure it out. :)

**Comment by mdazharuddin1011999** [comment]
@manesvenom were you able to figure out the problem?

**Comment by manesvenom** [comment]
Yes, follow the suggestion   Injecting UI consumable streams https://www.filledstacks.com/post/flutter-provider-v3-architecture/
