### ISSUE TITLE
This expression has type 'void' and can't be used.     return navigatorKey.currentState.pop();

### ISSUE THREAD

**Issue by hemendrasundar** [FilledStacks/flutter-tutorials#54]
in 034-flutter-web-part3-template-layouts i am getting this error plzz help me how to resolve this.
![Screenshot (156)](https://user-images.githubusercontent.com/11142691/78348901-682a6180-75c0-11ea-8d84-cc54f9478de8.png)

**Comment by FilledStacks** [comment]
Change the function return type to void and remove the return word.

________________________________

**Comment by hemendrasundar** [comment]
thanks working now
