### ISSUE TITLE
Not relevant

### ISSUE THREAD

**Issue by jpablogn** [FilledStacks/flutter-tutorials#57]
Hi,
From your repo  "tutorials / provider_architecture / start": 
- In "pubspec.yaml" is written " get_it:" with no version: 
   This generates an error in "locator.dart" in the line "GetIt locator = GetIt.instance;"
- Adding the versión  "get_it: ^4.0.1" solve this error.

Thank you for your excellent work/tutorial.
J. Pablo.

**Comment by FilledStacks** [comment]
Awesome.Thanks for sharing. I don't get that error but I assume it's because of a get_it version change

**Comment by jpablogn** [comment]
Yep, I think so.
In [your article about Get_It](https://www.filledstacks.com/snippet/dependency-injection-in-flutter/) you use **get_it: ^1.0.3** and you create the object like this "**GetIt locator = GetIt();**" (may be time to update :) ). I think this change probably came with version 2.0.0. of Get_It.
Thanks to you (amaizing work of knowledge spread).

**Comment by FilledStacks** [comment]
Aaah yes. That's a very old article. All the latest tutorials use the latest versions and syntax.
