### ISSUE TITLE
033-flutter-web-part2-responsive

### ISSUE THREAD

**Issue by Faiyyaz** [FilledStacks/flutter-tutorials#61]
Hey thanks for such a great tutorial but i found missing thing the mentioned tutorial

Open Drawer on IconButton onPressed functionality is missing

**Comment by Raptor121-SA** [comment]
@Faiyyaz That is easy to fix, Just add Scaffold.of(context).openDrawer() to the onPressed function.

**Comment by Faiyyaz** [comment]
Thanks :) @Raptor121-SA
