### ISSUE TITLE
InheretedWidgets

### ISSUE THREAD

**Issue by Aljulanda9** [FilledStacks/flutter-tutorials#63]
Hello! Thanks a lot for the tutorial. I built my app following your provider architecture and it's been amazing. 

Just wanted to ask you about the recommended way of accessing data from a parent widget in this architecture. Passing arguments through constructors from a parent to child doesn't seem to be as efficient as using say an InheritedWidget. How can we use something like inheretedWidget with your provider architecture? 

Again thanks a lot for your amazing tutorials!

**Comment by FilledStacks** [comment]
Hi, you're welcome :) 

Provider is a better version of inherited widget so I would pass the values using a provider like we do in the responsive ui tutorials.
