### ISSUE TITLE
Latest Flutter release breaks NavigationService

### ISSUE THREAD

**Issue by thedigitalpro** [FilledStacks/flutter-tutorials#65]
Hey Dane

The latest 1.17 release of flutter breaks the navigation service. The following error is returned:

lib/services/navigation_service.dart:9:40: Error: This expression has type 'void' and can't be used.
    return _navigationKey.currentState.pop();

**Comment by FilledStacks** [comment]
Hey @thedigitalpro ,
You can either remove the return statement or change the function signature to void or both.
