### ISSUE TITLE
010-provider-architecture Not load post

### ISSUE THREAD

**Issue by sercheo87** [FilledStacks/flutter-tutorials#69]
Hi, I has a problem when run [Final example](https://github.com/FilledStacks/flutter-tutorials/tree/master/010-provider-architecture/002-final) not load _**post**_ because is produced by `Provider.of<User>(context).id` in file **home_view.dart** has _**0**_ on first run.

**Comment by sercheo87** [comment]
I found difference when use `provider: ^2.0.1` run without problems but use `provider: ^4.0.4` is the problem the model not set value user id.

**Comment by FilledStacks** [comment]
Aaah, nice catch. You might have to handle your initial data different then. Check if there's updated docs and follow that from the provider readme

**Comment by quajodk** [comment]
I followed your tutorials to build an app same architecture as this the youtube tutorials. the issue I'm having is on app startup the `provider.of<User>(context)` is null. Though I'm managing that with a loader it throws the error on emulator.

**Comment by quajodk** [comment]
I found the issues it got to do with lazy loading of the create callback of provider in version 4, I just pass `lazy: false` to the provider.

**Comment by heinzan** [comment]
same too happen in me how solve that?My first time id is zero Please point me thanks.

**Comment by quajodk** [comment]
In the tutorial @FilledStacks used initial value in the user model which is passed to the provider in the first load. You don't necessarily need the initial values, so comment or take them out.

**Comment by FilledStacks** [comment]
@heinzan there's two solutions above your comment I hope you tried both. Update version to latest and set lazy to false.
