### ISSUE TITLE
Tutorial 10, final-no-getit git issue with package

### ISSUE THREAD

**Issue by mirkancal** [FilledStacks/flutter-tutorials#7]
Hello, I'm having this issue. Might be about git ref of provider package.

```
Git error. Command: git rev-list --max-count=1 proxy-provider
fatal: ambiguous argument 'proxy-provider': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:


'git <command> [<revision>...] -- [<file>...]'

pub get failed (69) -- attempting retry 5 in 16 seconds...

```

**Comment by FilledStacks** [comment]
As mentioned by Remi [here](https://github.com/FilledStacks/flutter-tutorials/pull/2#issue-280503020). This is just an example of how it **can** be done without get_it. This is not a working example. It's there specifically just to show how it'll be done, when proxy provider is merged into the package.
