### ISSUE TITLE
Refactoring DialogManager with using stacked_services plugin

### ISSUE THREAD

**Issue by volkangurol** [FilledStacks/flutter-tutorials#71]
Hi Dane, firstly thanks for everything you teach us. I keep my code clean for each iteration you provide new pattern / ways to better coding.

In your previous tutorials you created DialogManager and registerDialogListener in initState.

Now Im using your new library that is **stacked_services** and i refactored all my code with minimal changes but i'm struggling with DialogManager part. Can you show us how to refactor this part so that we can use this. Thank you.

**Comment by FilledStacks** [comment]
hi @volkangurol when using stacked services you don't need a manager. We use get for context less dialog managing. so as long as the get key is set as the navigation key, either through the navigation service or dialog service then you can show dialogs through the service without the manager.

**Comment by volkangurol** [comment]
Thank you for your response Dane, so i can remove safely builder part in MaterialApp.
