### ISSUE TITLE
Navigation service - Arguments Mistype

### ISSUE THREAD

**Issue by tonini46** [FilledStacks/flutter-tutorials#73]
Hi my problem occurs when I pass a _Map<String, dynamic>_ argument. I get the exception attached.

```
Map<String, dynamic> data = {
          "action": "forgot_password",
          "msisdn": "",
          "calling_code": "",
          "reset_code": ""
        };
_navigationService.replaceWith(Routes.pinResetOtpReceiveViewRoute, arguments: data);
```

And in the navigated page:
```
class PinResetOtpReceiveView extends StatelessWidget {
  const PinResetOtpReceiveView({Key key, this.changePinData}) : super(key: key);  
  final Map<String, dynamic> changePinData; .....
```
So my issue is how do I access the passed argument from my navigated page without getting the exception?
![Screenshot_20200602-171233 1](https://user-images.githubusercontent.com/7890110/83530407-5dbf1200-a4f4-11ea-9ec5-e5a2e215e0f9.jpg)

**Comment by FilledStacks** [comment]
Use the PinResetOtpReceiveViewArguments file it's auto generated when you generate a view that has parameters. you can just add all your parameters to the view and then it'll generate that class when your run the build_runner build command.

**Comment by tonini46** [comment]
Thanks, that was really helpful. You guys really come through for me.
