### ISSUE TITLE
010 - UserID not provided on first load

### ISSUE THREAD

**Issue by FrankDomburg** [FilledStacks/flutter-tutorials#77]
Seems a lazy loading issue somewhere.

When I enter a userID, the home_view comes with a name in the header, but no posts.
When I go back, enter the same userID, the posts become visible.

When I enter a userID, the home_view comes with a name in the header, but no posts.
When I go back, enter the a different userID, the correct posts become visible.

So suspect that userID becomes available to late for the getPosts function to work. But don't understand why, given that the header is displayed correctly.

**Comment by FrankDomburg** [comment]
I solved this by making the StreamProvider<User> in main.dart "lazy: false".

I am just not sure if this is the right approach.

**Comment by FilledStacks** [comment]
I think that is the right approach. I don't use the global streams in production. I mention in the video I'm only doing it to show that it's possible and what provider can do. But in production i don't use it.

**Comment by mdazharuddin1011999** [comment]
Hello @FilledStacks , I wanted to ask how should I implement themes(light and dark) without global streams?

When I was using redux, I was using a global `StreamBuilder`. Can you recommend a different way or give a hint how to implement it now?

**Comment by FilledStacks** [comment]
@mdazharuddin1011999 with a theme it's a bit different since it's consumed only within the UI part of the code. It's not actually used with business logic. I built a [Theme Manager here](https://www.filledstacks.com/snippet/build-a-theme-manager-in-flutter/) that you can look at. It uses a global stream.

**Comment by mdazharuddin1011999** [comment]
Thanks for the link, Sir!
