### ISSUE TITLE
change Text string

### ISSUE THREAD

**Issue by IanKettler** [FilledStacks/flutter-tutorials#8]
https://github.com/FilledStacks/flutter-tutorials/blob/e3d2345c06e10fafdf376aca2ad7efb05abbf634/014-provider-v3-updates/2-final/lib/ui/views/post_view.dart#L9

Change Text to `Text('Post View')`.

**Comment by FilledStacks** [comment]
Haha, thanks. Still working on this one, trying to finish the code tonight. I'll fix this up now.
