### ISSUE TITLE
No type DialogService is registered inside GetIt

### ISSUE THREAD

**Issue by akyjoe** [FilledStacks/flutter-tutorials#84]
This particular service is causing the issue while navigating into LoginScreen.

Referring to the tutorial https://github.com/FilledStacks/flutter-tutorials/tree/master/039-firebase-custom-start-user-profile

Inside the Login ModalView file:

`final DialogService _dialogService = locator<DialogService>();`

Above line of code is causing issue. Upon disabling this particular line and its instances, Login screen works, then it throws the next exception when we navigate to Register Screen, again the similar line of code is responsible for the exception.

The Flutter dependencies used in Pubsec.YAML are:

`dependencies:
  flutter:
    sdk: flutter
  get_it:
  stacked:
  firebase_auth:
  cloud_firestore:`

The Exception is as under:

`flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building LoginScreen:
flutter: No type DialogService is registered inside GetIt.
flutter:  Did you forget to pass an instance name?
flutter: (Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;did you
flutter: forget to register it?)
flutter: 'package:get_it/get_it_impl.dart':
flutter: Failed assertion: line 251 pos 14: 'instanceFactory != null'
flutter:
flutter: The relevant error-causing widget was:
flutter:   LoginScreen file:////lib/screens/router.dart:12:21
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _GetItImplementation._findFactoryByNameOrType (package:get_it/get_it_impl.dart:251:14)
flutter: #3      _GetItImplementation.get (package:get_it/get_it_impl.dart:263:27)
flutter: #4      _GetItImplementation.call (package:get_it/get_it_impl.dart:288:12)
flutter: #5      new LoginScreenModel (package:<some-pack-name>/screens/user/model/login.dart:11:47)
flutter: #6      LoginScreen.build.<anonymous closure> (package:<some-pack-name>/screens/user/login.dart:16:31)
flutter: #7      _ViewModelBuilderState._createViewModel (package:stacked/src/view_model_builder.dart:92:39)
flutter: #8      _ViewModelBuilderState.initState (package:stacked/src/view_model_builder.dart:82:7)
flutter: #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
flutter: #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
flutter: ...     Normal element mounting (30 frames)
flutter: #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
flutter: #41     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
flutter: ...     Normal element mounting (119 frames)
flutter: #160    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
flutter: #161    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
flutter: #162    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5580:32)
flutter: #163    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5957:17)
flutter: #164    Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
flutter: #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
flutter: #166    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
flutter: #167    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
flutter: #168    StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
flutter: #169    Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
flutter: #170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
flutter: #171    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
flutter: #172    ProxyElement.update (package:flutter/src/widgets/framework.dart:4862:5)
flutter: #173    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
flutter: #174    Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
flutter: #175    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
flutter: #176    Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
flutter: #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
flutter: #178    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
flutter: #179    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
flutter: #180    StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
flutter: #181    Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
flutter: #182    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
flutter: #183    Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
flutter: #184    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
flutter: #185    Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
flutter: #186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
flutter: #187    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
flutter: #188    StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
flutter: #189    Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
flutter: #190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
flutter: #191    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
flutter: #192    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
flutter: #193    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
flutter: #194    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
flutter: #195    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
flutter: #196    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
flutter: #197    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
flutter: #198    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
flutter: #202    _invoke (dart:ui/hooks.dart:261:10)
flutter: #203    _drawFrame (dart:ui/hooks.dart:219:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════`

**Comment by FilledStacks** [comment]
You should register the dialog service with get_it

**Comment by akyjoe** [comment]
With regards to your tutorial series, can you provide reference to the line registering with get_it? I've referred to the #39 tutorial. 

If you're referring to `locator.dart` then isn't it registered using ` locator.registerLazySingleton(() => DialogService());` code? It's refered from your code. Because other services like Navigation and Authentication are registered using the same way and working flawlessly. This Dialog one is causing issues for some reason.

**Comment by FilledStacks** [comment]
yes, that is what I'm reffering to. Make sure that it's registered before you try and use it. Add some logs after the dialog service registration and then add a log above where you're trying to get it and see which one prints first. If you're trying to get it before it's registered then it'll fail.

**Comment by akyjoe** [comment]
Here's the log:

`Restarted application in 1,350ms.
flutter: #Custom Log: Register Services!
flutter: #Custom Log: Registered Dialog Service (registerLazySingleton)!
flutter: #Custom Log: Registered Nav Service (registerLazySingleton)!
flutter: #Custom Log: Registered Auth Service (registerLazySingleton)!
flutter: #Custom Log: Registered Data Service (registerLazySingleton)!
flutter: #Custom Register Dialog Listener
flutter: No Logged in User
flutter: #Custom Log Building Login Screen!
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building LoginScreen:
flutter: No type DialogService is registered inside GetIt.
flutter:  Did you forget to pass an instance name?
flutter: (Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;did you
flutter: forget to register it?)`

The sequence looks right to me as it register before calling. I also noticed using breakpoints debugger, the exception originates in this return statement `return ViewModelBuilder<LoginScreenModel>.reactive(` and in this line of code `viewModelBuilder: () => LoginScreenModel(),`. The debugger does not reach the ViewModel file, perhaps is lost somewhere in the middle. Kindly suggest.

**Comment by akyjoe** [comment]
I removed the "stacked" package and installed it again yesterday and it worked. Since then it's working flawlessly.

**Comment by bradcroteau** [comment]
I'm having this same problem now.

On using any of my GetIt registered services I receive the same type of error: 

"Object/factory with  type DialogService is not registered inside GetIt. 
(Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
Did you forget to register it?)"

I've tried awaiting setupLocator() and get the same outcome. Adding the logging you mentioned above all of my locator.registerLazySingleton() calls occur prior to any call for the locator<service>() calls.

This is driving me nuts because it's simple code with no apparent reason not to work, but it's holding me up in refactoring to the MVVM architecture, the benefits of which my app definitely needs. Any new suggestions you might have will be endlessly appreciated!

**Comment by akyjoe** [comment]
> I'm having this same problem now.
> 
> On using any of my GetIt registered services I receive the same type of error:
> 
> "Object/factory with type DialogService is not registered inside GetIt.
> (Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
> Did you forget to register it?)"
> 
> I've tried awaiting setupLocator() and get the same outcome. Adding the logging you mentioned above all of my locator.registerLazySingleton() calls occur prior to any call for the locator() calls.
> 
> This is driving me nuts because it's simple code with no apparent reason not to work, but it's holding me up in refactoring to the MVVM architecture, the benefits of which my app definitely needs. Any new suggestions you might have will be endlessly appreciated!

Try to print the sequence of various method/function definitions you call starting from the main function. Use breakpoints while debugging to understand which particular value is Null during function call of Dialog Function. 

Also make sure that you using latest version of the flutter and its packages. Flutter versioning can be a big confusion, as those packages further download native Android and iOS packages.

**Comment by FilledStacks** [comment]
In addition to that run flutter pub upgrade to ensure the local packages are on the latest versions as well.
