### ISSUE TITLE
Clear back stack

### ISSUE THREAD

**Issue by h4h13** [FilledStacks/flutter-tutorials#99]
Hi, I'm new to this Architectures pattern that you're using, I got stumbled where I have to clear the back stack just like
`Navigator.of(context).pushAndRemoveUntil(newRoute, (route) => false);`  can you help me how to do this with `NavigationService` class 
*Sorry for my English.

**Comment by h4h13** [comment]
Sorry, I got it edited `NavigationService` with another method 
` Future<dynamic> navigateToPush(String routeName, {dynamic arguments}) {
    return navigatorKey.currentState
        .pushNamedAndRemoveUntil(routeName, (route) => false);
  }` 
Is this right?

**Comment by FilledStacks** [comment]
@h4h13 yes, the [NavigationService ](https://pub.dev/packages/stacked_services#navigation-service) has functions for this as well. The last 1 in the list.
